/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { db } from ".";
import { createTRPCRouter } from "../../trpc";
import { procedure } from "../../trpc";
import * as _Schema from '@zenstackhq/runtime/zod/input';
const $Schema: typeof _Schema = (_Schema as any).default ?? _Schema;
import { checkRead, checkMutate } from '../helper';

export default function createRouter() {
    return createTRPCRouter({

        aggregate: procedure.input($Schema.SurgeriesInputSchema.aggregate).query(({ ctx, input }) => checkRead(db(ctx).surgeries.aggregate(input as any))),

        createMany: procedure.input($Schema.SurgeriesInputSchema.createMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.createMany(input as any))),

        create: procedure.input($Schema.SurgeriesInputSchema.create).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.create(input as any))),

        deleteMany: procedure.input($Schema.SurgeriesInputSchema.deleteMany.optional()).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.deleteMany(input as any))),

        delete: procedure.input($Schema.SurgeriesInputSchema.delete).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.delete(input as any))),

        findFirst: procedure.input($Schema.SurgeriesInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).surgeries.findFirst(input as any))),

        findFirstOrThrow: procedure.input($Schema.SurgeriesInputSchema.findFirst.optional()).query(({ ctx, input }) => checkRead(db(ctx).surgeries.findFirstOrThrow(input as any))),

        findMany: procedure.input($Schema.SurgeriesInputSchema.findMany.optional()).query(({ ctx, input }) => checkRead(db(ctx).surgeries.findMany(input as any))),

        findUnique: procedure.input($Schema.SurgeriesInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).surgeries.findUnique(input as any))),

        findUniqueOrThrow: procedure.input($Schema.SurgeriesInputSchema.findUnique).query(({ ctx, input }) => checkRead(db(ctx).surgeries.findUniqueOrThrow(input as any))),

        groupBy: procedure.input($Schema.SurgeriesInputSchema.groupBy).query(({ ctx, input }) => checkRead(db(ctx).surgeries.groupBy(input as any))),

        updateMany: procedure.input($Schema.SurgeriesInputSchema.updateMany).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.updateMany(input as any))),

        update: procedure.input($Schema.SurgeriesInputSchema.update).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.update(input as any))),

        upsert: procedure.input($Schema.SurgeriesInputSchema.upsert).mutation(async ({ ctx, input }) => checkMutate(db(ctx).surgeries.upsert(input as any))),

        count: procedure.input($Schema.SurgeriesInputSchema.count.optional()).query(({ ctx, input }) => checkRead(db(ctx).surgeries.count(input as any))),

    }
    );
}
